on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.10
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.9'
    - run: raco pkg install --auto --batch snappy-lib/ snappy-test/ snappy/
    - run: raco test snappy-test/
